# Generated by Django 3.1 on 2020-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20200925_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='participants',
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
