# Generated by Django 3.1 on 2020-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_seminar_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
