# Generated by Django 3.1 on 2020-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
