# Generated by Django 3.1 on 2020-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_auto_20200927_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
