# Generated by Django 3.1 on 2020-10-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_auto_20200928_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
