# Generated by Django 3.1 on 2020-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_auto_20201006_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
